# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
print(s.split(' , '))

['Hi there Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [4]:
import numpy as np
array=np.zeros(10)
print('The array of 10 zeros');
print(array);

The array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
import numpy as np
array=np.ones(10)*5
print('The array of 10 fives');
print(array);

The array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [6]:
import numpy as np
array=np.arange(20,35,2);
print('The array of all even integers from 20 to 35 are:');
print(array);

The array of all even integers from 20 to 35 are:
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [8]:
import numpy as np
a=np.array([1,2,3]);
b=np.array([4,5,6]);
con=np.concatenate((a,b),axis=0);
print(con)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [9]:
import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)


   Name  Age
0   tom   10
1  nick   15
2  juli   14


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [27]:
import pandas as pd
dates = pd.date_range(start ='1-1-2023',end ='02-10-2023')
for val in dates:
print(val)



<class 'IndentationError'>: expected an indented block after 'for' statement on line 3 (<ipython-input-27-b80dc72f4e28>, line 4)

In [ ]:
## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [12]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['S.No','Tag', 'number'])
print(df)


   S.No  Tag  number
0     1  aaa      22
1     2  bbb      25
2     3  ccc      24
